[package]
name = "digits_sum"
version = "0.1.0"
authors = ["1kh4l <jhon.pantoja@correounivalle.edu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
